# MA3K7 Assignment 1

Name - Timothy Yap

Student ID - 21611367

## Code to find bracelet sequence

In [178]:
# Libraries
import numpy as np
import scipy
import matplotlib.pyplot as plt


# Bracelet sequence for 1, 5
# Setting Initial Conditions
x0 = 1
x1 = 5
seq = np.array([x0, x1])
test = 0


# Calculating first step
x_n = seq[-2] + seq[-1]
x_n = x_n % 10
seq = np.append(seq, [x_n])


# Loop until starting terms are regenerated
while test == 0:
    # Check for starting terms
    if (seq[-2] != x0) | (seq[-1] != x1):
        x_n = seq[-2] + seq[-1]
        x_n = x_n % 10
        seq = np.append(seq, [x_n])
    # Finshes by printing bracelet and size
    else:
        seq = seq[0 : -2]
        print(seq)
        print(seq.size)
        test = 1


[1 5 6 1 7 8 5 3 8 1 9 0 9 9 8 7 5 2 7 9 6 5 1 6 7 3 0 3 3 6 9 5 4 9 3 2 5
 7 2 9 1 0 1 1 2 3 5 8 3 1 4 5 9 4 3 7 0 7 7 4]
60


In [240]:
# Helping print LaTeX code to print terms
def latexPrint(sequence):
    seqLen = 2 * sequence.size 
    for i in range(seqLen):
        if i/2 % 1 == 0:
            x = int(i/2)
            print(sequence[x], "" , end="")
        if i/2 % 1 != 0:
            print("\\ ", end="")
            
latexPrint(seq)

1 \ 5 \ 6 \ 1 \ 7 \ 8 \ 5 \ 3 \ 8 \ 1 \ 9 \ 0 \ 9 \ 9 \ 8 \ 7 \ 5 \ 2 \ 7 \ 9 \ 6 \ 5 \ 1 \ 6 \ 7 \ 3 \ 0 \ 3 \ 3 \ 6 \ 9 \ 5 \ 4 \ 9 \ 3 \ 2 \ 5 \ 7 \ 2 \ 9 \ 1 \ 0 \ 1 \ 1 \ 2 \ 3 \ 5 \ 8 \ 3 \ 1 \ 4 \ 5 \ 9 \ 4 \ 3 \ 7 \ 0 \ 7 \ 7 \ 4 \ 

In [273]:
# Creating a function to be used later
def bracelet(x0, x1):
    # Setting Initial Conditions
    seq = np.array([x0, x1])
    test = 0

    # Calculating first step
    x_n = seq[-2] + seq[-1]
    x_n = x_n % 10
    seq = np.append(seq, [x_n])

    # Loop until starting terms are regenerated
    while test == 0:
        # Check for starting terms
        if (seq[-2] != x0) | (seq[-1] != x1):
            x_n = seq[-2] + seq[-1]
            x_n = x_n % 10
            seq = np.append(seq, [x_n])
        # Finshes by printing bracelet and size
        else:
            test = 1
            return seq[0: -2], seq.size - 2

In [255]:
# Checking Conjecture 1 (if all pairs in one sequence makes the same sequence)
for i in range(59):
    con1, con2 = bracelet(seq[i], seq[i + 1])
    print("Sequence:", con1, "\nSize:" , con2)
#Didn't check (4, 1) but can tell from the rest

Sequence: [1 5 6 1 7 8 5 3 8 1 9 0 9 9 8 7 5 2 7 9 6 5 1 6 7 3 0 3 3 6 9 5 4 9 3 2 5
 7 2 9 1 0 1 1 2 3 5 8 3 1 4 5 9 4 3 7 0 7 7 4 1 5] 
Size: 60
Sequence: [5 6 1 7 8 5 3 8 1 9 0 9 9 8 7 5 2 7 9 6 5 1 6 7 3 0 3 3 6 9 5 4 9 3 2 5 7
 2 9 1 0 1 1 2 3 5 8 3 1 4 5 9 4 3 7 0 7 7 4 1 5 6] 
Size: 60
Sequence: [6 1 7 8 5 3 8 1 9 0 9 9 8 7 5 2 7 9 6 5 1 6 7 3 0 3 3 6 9 5 4 9 3 2 5 7 2
 9 1 0 1 1 2 3 5 8 3 1 4 5 9 4 3 7 0 7 7 4 1 5 6 1] 
Size: 60
Sequence: [1 7 8 5 3 8 1 9 0 9 9 8 7 5 2 7 9 6 5 1 6 7 3 0 3 3 6 9 5 4 9 3 2 5 7 2 9
 1 0 1 1 2 3 5 8 3 1 4 5 9 4 3 7 0 7 7 4 1 5 6 1 7] 
Size: 60
Sequence: [7 8 5 3 8 1 9 0 9 9 8 7 5 2 7 9 6 5 1 6 7 3 0 3 3 6 9 5 4 9 3 2 5 7 2 9 1
 0 1 1 2 3 5 8 3 1 4 5 9 4 3 7 0 7 7 4 1 5 6 1 7 8] 
Size: 60
Sequence: [8 5 3 8 1 9 0 9 9 8 7 5 2 7 9 6 5 1 6 7 3 0 3 3 6 9 5 4 9 3 2 5 7 2 9 1 0
 1 1 2 3 5 8 3 1 4 5 9 4 3 7 0 7 7 4 1 5 6 1 7 8 5] 
Size: 60
Sequence: [5 3 8 1 9 0 9 9 8 7 5 2 7 9 6 5 1 6 7 3 0 3 3 6 9 5 4 9 3 2 5 7 2 9 1 0 1
 1 2 3 5 8 3 1 4 5 9 4 3 7 0 7 7 

In [239]:
# Printing all pairs and sizes
for i in range(10):
    for j in range(10):
        seq1, seq2 = bracelet(i, j)
        print("Sequence:", seq1, "\nSize:" , seq2)

Sequence: [0] 
Size: 1
Sequence: [0 1 1 2 3 5 8 3 1 4 5 9 4 3 7 0 7 7 4 1 5 6 1 7 8 5 3 8 1 9 0 9 9 8 7 5 2
 7 9 6 5 1 6 7 3 0 3 3 6 9 5 4 9 3 2 5 7 2 9 1] 
Size: 60
Sequence: [0 2 2 4 6 0 6 6 2 8 0 8 8 6 4 0 4 4 8 2] 
Size: 20
Sequence: [0 3 3 6 9 5 4 9 3 2 5 7 2 9 1 0 1 1 2 3 5 8 3 1 4 5 9 4 3 7 0 7 7 4 1 5 6
 1 7 8 5 3 8 1 9 0 9 9 8 7 5 2 7 9 6 5 1 6 7 3] 
Size: 60
Sequence: [0 4 4 8 2 0 2 2 4 6 0 6 6 2 8 0 8 8 6 4] 
Size: 20
Sequence: [0 5 5] 
Size: 3
Sequence: [0 6 6 2 8 0 8 8 6 4 0 4 4 8 2 0 2 2 4 6] 
Size: 20
Sequence: [0 7 7 4 1 5 6 1 7 8 5 3 8 1 9 0 9 9 8 7 5 2 7 9 6 5 1 6 7 3 0 3 3 6 9 5 4
 9 3 2 5 7 2 9 1 0 1 1 2 3 5 8 3 1 4 5 9 4 3 7] 
Size: 60
Sequence: [0 8 8 6 4 0 4 4 8 2 0 2 2 4 6 0 6 6 2 8] 
Size: 20
Sequence: [0 9 9 8 7 5 2 7 9 6 5 1 6 7 3 0 3 3 6 9 5 4 9 3 2 5 7 2 9 1 0 1 1 2 3 5 8
 3 1 4 5 9 4 3 7 0 7 7 4 1 5 6 1 7 8 5 3 8 1 9] 
Size: 60
Sequence: [1 0 1 1 2 3 5 8 3 1 4 5 9 4 3 7 0 7 7 4 1 5 6 1 7 8 5 3 8 1 9 0 9 9 8 7 5
 2 7 9 6 5 1 6 7 3 0 3 3 6 9 5 4 9 3 2 5 7 2 

In [278]:
# Check for unique sets
def checkUnique(x):
    checkSet = set()
    startPair = set()
    for i in range(x):
        for j in range(x):
            seq1, _ = bracelet(i, j)
            sortSeq = tuple(np.sort(seq1))
            if sortSeq not in checkSet:
                checkSet.add(sortSeq)
                startPair.add((i, j))
    print(startPair)

checkUnique(10)

{(0, 1), (0, 0), (0, 2), (2, 6), (0, 5), (1, 3)}


In [260]:
# Printing LaTeX code for other all unique bracelets
latSeq, latSiz = bracelet(0, 0)
latexPrint(latSeq)
print("Size", latSiz)
latSeq, latSiz = bracelet(0, 1)
latexPrint(latSeq)
print("Size", latSiz)
latSeq, latSiz = bracelet(0, 2)
latexPrint(latSeq)
print("Size", latSiz)
latSeq, latSiz = bracelet(0, 5)
latexPrint(latSeq)
print("Size", latSiz)
latSeq, latSiz = bracelet(1, 3)
latexPrint(latSeq)
print("Size", latSiz)
latSeq, latSiz = bracelet(2, 6)
latexPrint(latSeq)
print("Size", latSiz)

0 \ 0 \ 0 \ Size 1
0 \ 1 \ 1 \ 2 \ 3 \ 5 \ 8 \ 3 \ 1 \ 4 \ 5 \ 9 \ 4 \ 3 \ 7 \ 0 \ 7 \ 7 \ 4 \ 1 \ 5 \ 6 \ 1 \ 7 \ 8 \ 5 \ 3 \ 8 \ 1 \ 9 \ 0 \ 9 \ 9 \ 8 \ 7 \ 5 \ 2 \ 7 \ 9 \ 6 \ 5 \ 1 \ 6 \ 7 \ 3 \ 0 \ 3 \ 3 \ 6 \ 9 \ 5 \ 4 \ 9 \ 3 \ 2 \ 5 \ 7 \ 2 \ 9 \ 1 \ 0 \ 1 \ Size 60
0 \ 2 \ 2 \ 4 \ 6 \ 0 \ 6 \ 6 \ 2 \ 8 \ 0 \ 8 \ 8 \ 6 \ 4 \ 0 \ 4 \ 4 \ 8 \ 2 \ 0 \ 2 \ Size 20
0 \ 5 \ 5 \ 0 \ 5 \ Size 3
1 \ 3 \ 4 \ 7 \ 1 \ 8 \ 9 \ 7 \ 6 \ 3 \ 9 \ 2 \ 1 \ 3 \ Size 12
2 \ 6 \ 8 \ 4 \ 2 \ 6 \ Size 4


In [290]:
# Extending with Python
def modBrace(x0, x1, mod):
    # Setting Initial Conditions
    seq = np.array([x0, x1])
    test = 0

    # Calculating first step
    x_n = seq[-2] + seq[-1]
    x_n = x_n % mod
    seq = np.append(seq, [x_n])

    # Loop until starting terms are regenerated
    while test == 0:
        # Check for starting terms
        if (seq[-2] != x0) | (seq[-1] != x1):
            x_n = seq[-2] + seq[-1]
            x_n = x_n % mod
            seq = np.append(seq, [x_n])
        # Finshes by printing bracelet and size
        else:
            test = 1
            return seq[0:-2], seq.size - 2

# Check for unique sets
def checkUniMod(x):
    checkSet = set()
    startPair = set()
    for i in range(x):
        for j in range(x):
            seq1, seq2 = modBrace(i, j, x)
            sortSeq = tuple(np.sort(seq1))
            if sortSeq not in checkSet:
                print(seq1, seq2)
                checkSet.add(sortSeq)
                startPair.add((i, j))
    print(startPair, len(startPair))


checkUniMod(1)
print("")
checkUniMod(2)
print("")
checkUniMod(3)
print("")
checkUniMod(4)
print("")
checkUniMod(5)
print("")
checkUniMod(6)
print("")
checkUniMod(7)
print("")
checkUniMod(8)
print("")
checkUniMod(9)
print("")
checkUniMod(10)

[0] 1
{(0, 0)} 1

[0] 1
[0 1 1] 3
{(0, 1), (0, 0)} 2

[0] 1
[0 1 1 2 0 2 2 1] 8
{(0, 1), (0, 0)} 2

[0] 1
[0 1 1 2 3 1] 6
[0 2 2] 3
[0 3 3 2 1 3] 6
{(0, 1), (0, 2), (0, 3), (0, 0)} 4

[0] 1
[0 1 1 2 3 0 3 3 1 4 0 4 4 3 2 0 2 2 4 1] 20
[1 3 4 2] 4
{(0, 1), (1, 3), (0, 0)} 3

[0] 1
[0 1 1 2 3 5 2 1 3 4 1 5 0 5 5 4 3 1 4 5 3 2 5 1] 24
[0 2 2 4 0 4 4 2] 8
[0 3 3] 3
{(0, 1), (0, 2), (0, 3), (0, 0)} 4

[0] 1
[0 1 1 2 3 5 1 6 0 6 6 5 4 2 6 1] 16
[0 2 2 4 6 3 2 5 0 5 5 3 1 4 5 2] 16
[0 3 3 6 2 1 3 4 0 4 4 1 5 6 4 3] 16
{(0, 1), (0, 2), (0, 3), (0, 0)} 4

[0] 1
[0 1 1 2 3 5 0 5 5 2 7 1] 12
[0 2 2 4 6 2] 6
[0 3 3 6 1 7 0 7 7 6 5 3] 12
[0 4 4] 3
[0 6 6 4 2 6] 6
[1 3 4 7 3 2 5 7 4 3 7 2] 12
[1 4 5 1 6 7 5 4 1 5 6 3] 12
{(0, 1), (0, 4), (0, 0), (0, 3), (1, 4), (0, 6), (0, 2), (1, 3)} 8

[0] 1
[0 1 1 2 3 5 8 4 3 7 1 8 0 8 8 7 6 4 1 5 6 2 8 1] 24
[0 2 2 4 6 1 7 8 6 5 2 7 0 7 7 5 3 8 2 1 3 4 7 2] 24
[0 3 3 6 0 6 6 3] 8
[0 4 4 8 3 2 5 7 3 1 4 5 0 5 5 1 6 7 4 2 6 8 5 4] 24
{(0, 1), (0, 4), (0, 0), (0, 3