# MA3K7 Assignment 2

Name - Timothy Yap

Student ID - 21611367

## Code to find possible matrices and their determinant

In [1]:
# Libraries
import numpy as np
import scipy
import itertools
import matplotlib.pyplot as plt

# Shorter calculate determinant function
def calDet(mat):
    return np.linalg.det(mat)

# Creating function to create possible matrices
def matrixGen(num):
    matList = []
    # n even
    if num % 2 == 0:
        check = (num ** 2) / 2
            
    # n odd
    if num % 2 == 1:
        # Only testing if 0-player goes first
        check = ((num ** 2) - 1) / 2
    
    # Creating every possible matrix
    for i in range(2 ** (num ** 2)):
            # Using binary numbers to fill in matrix
            binRep = bin(i)[2:].zfill(num ** 2)
            matTemp = np.array(list(map(int, binRep))).reshape(num, num)               
            
            # Taking only possible matrices
            if np.sum(matTemp) == check:
                matList.append(matTemp)
    return matList

# Listing valid matrices with the Determinant
def matrixList(n):
    matSet = matrixGen(n)
    
    for mat in matSet:
        det = calDet(mat)
        print(mat)
        print("Determinant:", det, "\n")

# Testing with 2x2 case
n = 2
matrixList(n)

[[0 0]
 [1 1]]
Determinant: 0.0 

[[0 1]
 [0 1]]
Determinant: 0.0 

[[0 1]
 [1 0]]
Determinant: -1.0 

[[1 0]
 [0 1]]
Determinant: 1.0 

[[1 0]
 [1 0]]
Determinant: 0.0 

[[1 1]
 [0 0]]
Determinant: 0.0 



In [2]:
# 3x3 case
# Removing all cases where there are a 0 row and columns
def filterMat(mat):
    retList = []
    # Looping over all matrices
    for matrix in mat:
        if not (np.any((matrix == 0).all(axis=1)) or np.any((matrix == 0).all(axis=0))):
            retList.append(matrix)
    return retList

# Removing all matrix if det != 0
def onlyDet0(mat):
    retList = []
    for matrix in mat:
        if calDet(matrix) == 0:
            retList.append(matrix)
    return retList

# Listing valid matrices with the Determinant
def matrixDet0(n):
    # Generate all matrices when 0-player goes first
    matSet = matrixGen(n)
    print("Number of all possible games:", len(matSet))
    
    # Filter games with 0 row
    filteredMat = filterMat(matSet)
    print("Number of games with 0 row or column:", len(filteredMat))
    
    # Removing games with non-zero det
    winCase = onlyDet0(filteredMat)
    print("Possible winnable games:", len(winCase))
    
    for mat in winCase:
        det = calDet(mat)
        print(mat)
        print("Determinant:", det, "\n")

# Printing the left over cases
n = 3

matrixDet0(n)

Number of all possible games: 126
Number of games with 0 row or column: 45
Possible winnable games: 9
[[0 0 1]
 [0 0 1]
 [1 1 0]]
Determinant: 0.0 

[[0 0 1]
 [1 1 0]
 [0 0 1]]
Determinant: 0.0 

[[0 1 0]
 [0 1 0]
 [1 0 1]]
Determinant: 0.0 

[[0 1 0]
 [1 0 1]
 [0 1 0]]
Determinant: 0.0 

[[0 1 1]
 [1 0 0]
 [1 0 0]]
Determinant: 0.0 

[[1 0 0]
 [0 1 1]
 [1 0 0]]
Determinant: 0.0 

[[1 0 0]
 [1 0 0]
 [0 1 1]]
Determinant: 0.0 

[[1 0 1]
 [0 1 0]
 [0 1 0]]
Determinant: 0.0 

[[1 1 0]
 [0 0 1]
 [0 0 1]]
Determinant: 0.0 



## Exploring the case if we go Second

In [3]:
# Libraries
import numpy as np
import scipy
import itertools
import matplotlib.pyplot as plt

# Shorter calculate determinant function
def calDet(mat):
    return np.linalg.det(mat)

# Creating function to create possible matrices
def matrixGen(num):
    matList = []
    # n even
    if num % 2 == 0:
        check = (num ** 2) / 2
            
    # n odd
    if num % 2 == 1:
        # Only testing if 0-player goes second
        check = ((num ** 2) + 1) / 2
    
    # Creating every possible matrix
    for i in range(2 ** (num ** 2)):
            # Using binary numbers to fill in matrix
            binRep = bin(i)[2:].zfill(num ** 2)
            matTemp = np.array(list(map(int, binRep))).reshape(num, num)               
            
            # Taking only possible matrices
            if np.sum(matTemp) == check:
                matList.append(matTemp)
    return matList

# Listing valid matrices with the Determinant
def matrixList(n):
    matSet = matrixGen(n)
    
    for mat in matSet:
        det = calDet(mat)
        print(mat)
        print("Determinant:", det, "\n")

# Testing with 2x2 case
n = 2
matrixList(n)

# 3x3 case
# Removing all cases where there are a 0 row and columns
def filterMat(mat):
    retList = []
    # Looping over all matrices
    for matrix in mat:
        if not (np.any((matrix == 0).all(axis=1)) or np.any((matrix == 0).all(axis=0))):
            retList.append(matrix)
    return retList

# Removing all matrix if det != 0
def onlyDet0(mat):
    retList = []
    for matrix in mat:
        if calDet(matrix) == 0:
            retList.append(matrix)
    return retList

# Listing valid matrices with the Determinant
def matrixDet0(n):
    # Generate all matrices when 0-player goes first
    matSet = matrixGen(n)
    print("Number of all possible games:", len(matSet))
    
    # Filter games with 0 row
    filteredMat = filterMat(matSet)
    print("Number of games with 0 row or column:", len(filteredMat))
    
    # Removing games with non-zero det
    winCase = onlyDet0(filteredMat)
    print("Possible winnable games:", len(winCase))
    
    print("Some possible cases:")
    for mat in winCase[:25:5]:
        det = calDet(mat)
        print(mat)
        print("Determinant:", det, "\n")

# Printing the left over cases
n = 3
matrixDet0(n)

[[0 0]
 [1 1]]
Determinant: 0.0 

[[0 1]
 [0 1]]
Determinant: 0.0 

[[0 1]
 [1 0]]
Determinant: -1.0 

[[1 0]
 [0 1]]
Determinant: 1.0 

[[1 0]
 [1 0]]
Determinant: 0.0 

[[1 1]
 [0 0]]
Determinant: 0.0 

Number of all possible games: 126
Number of games with 0 row or column: 90
Possible winnable games: 18
Some possible cases:
[[0 0 1]
 [0 0 1]
 [1 1 1]]
Determinant: 0.0 

[[0 1 0]
 [1 1 1]
 [0 1 0]]
Determinant: 0.0 

[[1 0 0]
 [1 1 1]
 [1 0 0]]
Determinant: 0.0 

[[1 1 1]
 [0 0 1]
 [0 0 1]]
Determinant: 0.0 



In [4]:
n = 4
matrixDet0(n)
# Too many cases to look over
# Number of all possible games: 12870
# Number of games with 0 row or column: 9066
# Possible winnable games: 3738

Number of all possible games: 12870
Number of games with 0 row or column: 9066
Possible winnable games: 3738
Some possible cases:
[[0 0 0 1]
 [0 0 0 1]
 [0 0 1 1]
 [1 1 1 1]]
Determinant: 0.0 

[[0 0 0 1]
 [0 0 0 1]
 [0 1 1 1]
 [1 1 1 0]]
Determinant: 0.0 

[[0 0 0 1]
 [0 0 0 1]
 [1 0 1 1]
 [1 1 1 0]]
Determinant: 0.0 

[[0 0 0 1]
 [0 0 0 1]
 [1 1 1 0]
 [0 1 1 1]]
Determinant: 0.0 

[[0 0 0 1]
 [0 0 0 1]
 [1 1 1 1]
 [0 1 0 1]]
Determinant: 0.0 



In [5]:
# Function for copycat strategy only for even numbers
def copycatEven(num):
    matList = []
    for i in range(2 ** (num * int(num / 2))):
    # Using binary numbers to fill in matrix
        binRep = bin(i)[2:].zfill(num * int(num / 2))
        # Matrix that we copy and invert
        matTemp = np.array(list(map(int, binRep))).reshape(num, int(num / 2)) 
        matNew = np.zeros((num, num))
        matNew[:, ::2] = matTemp  # Copy original columns to even columns
        matNew[:, 1::2] = 1 - matTemp  # Invert and copy original columns to odd columns
        
        matList.append(matNew)

    return matList

# Listing valid matrices with the Determinant
def ccPrintEven(num):
    matrix = copycatEven(num)
    for mat in matrix[::43]:
        det = calDet(mat)
        print(mat)
        print("Determinant:", det, "\n")

# Prints 10 out of the 2^8 different possibilites
print("Printing 6 cases:")
ccPrintEven(4)

Printing 6 cases:
[[0. 1. 0. 1.]
 [0. 1. 0. 1.]
 [0. 1. 0. 1.]
 [0. 1. 0. 1.]]
Determinant: 0.0 

[[0. 1. 0. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 0. 1. 0.]]
Determinant: 0.0 

[[0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [1. 0. 0. 1.]]
Determinant: 0.0 

[[1. 0. 0. 1.]
 [0. 1. 0. 1.]
 [0. 1. 0. 1.]
 [0. 1. 1. 0.]]
Determinant: 0.0 

[[1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]]
Determinant: 0.0 

[[1. 0. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [1. 0. 1. 0.]]
Determinant: 0.0 



In [6]:
# Checking if there are any non-zero determinants
def detCheckEven(num):
    test = 0
    matList = copycatEven(num)
    for mat in matList:
        check = calDet(mat)
        test += check
    return test

# Checking if all possible copycat strategies return a 0 determinant
print(detCheckEven(4))
print(detCheckEven(6))

0.0
0.0


In [7]:
# Checking some cases for n = 8
num = 8
matList = []
for i in range(0, 2 ** (num * int(num / 2)), 2 ** 12):
# Using binary numbers to fill in matrix
    binRep = bin(i)[2:].zfill(num * int(num / 2))
    # Matrix that we copy and invert
    matTemp = np.array(list(map(int, binRep))).reshape(num, int(num / 2)) 
    matNew = np.zeros((num, num))
    matNew[:, ::2] = matTemp  # Copy original columns to even columns
    matNew[:, 1::2] = 1 - matTemp  # Invert and copy original columns to odd columns

    matList.append(matNew)

test = 0
for mat in matList:
    check = calDet(mat)
    test += check
print(test)

0.0


In [8]:
A = np.array([[1, 0, 1],[0, 1, 0]])
B = np.array([[1, 0],[1, 0],[0, 1]])
Temp = A @ B
print(calDet(Temp))

A = np.array([[1, 0, 1],[0, 1, 0]])
B = np.array([[1, 0],[0, 1],[0, 1]])
Temp = A @ B
print(calDet(Temp))

A = np.array([[0, 0, 0],[1, 0, 1]])
B = np.array([[1, 0],[1, 1],[0, 1]])
Temp = A @ B
print(calDet(Temp))

-1.0
1.0
0.0
